import { IsBoolean, IsNotEmpty, IsString } from 'class-validator';

/**
 * Data transfer object for creating a workspace.
 * `id` and `members` are excluded since the former is generated by database,
 * and the latter is latter is added after a workspace is created.
 */
export class CreateWorkspaceDto {
  @IsNotEmpty()
  @IsString()
  name: string;

  @IsNotEmpty()
  @IsString()
  domain: string;

  @IsNotEmpty()
  @IsBoolean()
  samlEnabled: boolean;
}
