import { IsNotEmpty, IsEmail, IsString } from 'class-validator';

/**
 * Data transfer object for creating a user.
 * `id` and `workspaces` are excluded since the former is generated by database,
 * and the latter is added after a user is created.
 */
export class CreateUserDto {
  @IsNotEmpty()
  @IsString()
  firstName: string;

  @IsNotEmpty()
  @IsString()
  lastName: string;

  @IsNotEmpty()
  @IsEmail()
  email: string;
}
