import { IsNotEmpty, IsEmail, IsString, IsArray } from 'class-validator';

/**
 * Data transfer object for creating a user.
 * `id` is not included because it is generated by the database.
 */
export class CreateUserDto {
  @IsNotEmpty()
  @IsString()
  firstName: string;

  @IsNotEmpty()
  @IsString()
  lastName: string;

  @IsNotEmpty()
  @IsEmail()
  email: string;

  @IsArray()
  workspaces: string[];
}
